# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GithubApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GithubApp
pod 'SwiftLint'
pod 'Alamofire'
pod 'SnapKit'
pod 'RxSwift'
pod 'RxCocoa'
pod 'RxViewController'
end
